# Generated by Django 2.2 on 2019-04-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_publisher'),
        ('catalog', '0003_author'),
    ]

    operations = [
    ]
