# Generated by Django 2.2 on 2019-04-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_merge_20190429_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='middle name',
        ),
        migrations.AddField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='catalog.Author'),
        ),
    ]
